services:
  db:
    image: postgres:16
    container_name: skillbridge-db
    environment:
      POSTGRES_USER: skilluser
      POSTGRES_PASSWORD: skillpassword
      POSTGRES_DB: skillbridge_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: skillbridge-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data

volumes:
  pgdata:
  minio-data: